### ISSUE TITLE
Sapling does not work with Plant-in-a-jar

### ISSUE THREAD

**Issue by spoorn** [spoorn/SpoornPacks#4]
^

**Comment by spoorn** [comment]
The error I got:

```
[20:41:47] [Render thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2794.method_33730()" because "$$0" is null
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_5868.<init>(class_5868.java:11)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_5444.<init>(class_5444.java:22)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_6796.method_39644(class_6796.java:40)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_3226.method_14271(class_3226.java:28)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_3150.method_13151(class_3150.java:25)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_3031.method_40163(class_3031.java:163)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2975.method_12862(class_2975.java:27)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2647.method_11431(class_2647.java:30)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2473.method_10507(class_2473.java:49)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2473.doTheGrow(class_2473.java:1017)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at io.github.coolmineman.plantinajar.tree.TreeMan.genTree(TreeMan.java:55)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at io.github.coolmineman.plantinajar.JarBlockEntity.tick(JarBlockEntity.java:124)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at io.github.coolmineman.plantinajar.JarBlock.lambda$getTicker$0(JarBlock.java:33)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1937.method_18471(class_1937.java:475)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_638.method_18116(class_638.java:204)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1574(class_310.java:1761)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1091)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:737)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:236)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[20:41:47] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by spoorn** [comment]
Better log:

```
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.gen.chunk.ChunkGenerator.getMinimumY()" because "generator" is null
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.gen.HeightContext.<init>(HeightContext.java:14)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.gen.feature.FeaturePlacementContext.<init>(FeaturePlacementContext.java:26)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.gen.feature.PlacedFeature.generateUnregistered(PlacedFeature.java:34)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.gen.feature.RandomFeatureEntry.generate(RandomFeatureEntry.java:28)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.gen.feature.RandomFeature.generate(RandomFeature.java:31)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.gen.feature.Feature.generateIfValid(Feature.java:218)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature.java:26)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.block.sapling.SaplingGenerator.generate(SaplingGenerator.java:30)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.block.SaplingBlock.generate(SaplingBlock.java:59)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.block.SaplingBlock.doTheGrow(SaplingBlock.java:517)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at io.github.coolmineman.plantinajar.tree.TreeMan.genTree(TreeMan.java:55)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at io.github.coolmineman.plantinajar.JarBlockEntity.tick(JarBlockEntity.java:123)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at io.github.coolmineman.plantinajar.JarBlock.lambda$getTicker$0(JarBlock.java:33)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.chunk.WorldChunk$DirectBlockEntityTickInvoker.tick(WorldChunk.java:579)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.chunk.WorldChunk$WrappedBlockEntityTickInvoker.tick(WorldChunk.java:579)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.world.World.tickBlockEntities(World.java:457)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.world.ClientWorld.tickEntities(ClientWorld.java:246)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1625)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1043)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:724)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:214)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[21:31:37] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

**Comment by spoorn** [comment]
This was fixed in https://github.com/CoolMineman/Plant-In-A-Jar/commit/1bb1fb96a92127880183affb13f89d9bcd36993e and https://github.com/CoolMineman/Plant-In-A-Jar/commit/afdd97749ca2b15b497e84e2a1b6f44dd0426a8d after contacting the dev on discord

The Pink Blossom Sapling still isn't growing in the Plant Jar though
